services:
  app:
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: Dockerfile.dev
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    image: t3-app
    depends_on:
      - "db"
    networks:
      - default

  db:
    image: mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_DATABASE: aoe-tactician-main
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    command: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - default

volumes:
  mysql:

networks:
  default: